[tool.poetry]
name = "dhall"
version = "0.0.1"
description = "A Python module for reading Dhall lang"
authors = ["Tristan Cacqueray <tdecacqu@redhat.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/TristanCacqueray/python-dhall"
keywords = ["dhall", "python"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
pylint = "^1.9"
flake8 = "^3.5"
wheel = "*"
pytest-runner = "*"
pytest-benchmark = "*"
simplejson = "*"
ujson = "*"
yajl = "*"
orjson = { version = "*", markers = "python_version < '3.8'" }
python-rapidjson = "*"
hypothesis = "*"
autopep8 = "*"
maturin = "==0.7.7"
